version: "3.8"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=tech_certification_api
    volumes:
      - pg-data:/bitnami/postgresql

volumes:
  pg-data: