version: "3.8"

services:
  database:
    container_name: tech-certification-system-pg
    image: postgres
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tech_certification_system
    volumes:
      - ./db-data:/var/lib/postgresql/data
