version: "3.8"

services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tech_certification_api
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
