version: "3.8"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tech_certification_system
    volumes:
      - tech-certification-system-pg-data:/bitnami/postgresql

volumes:
  tech-certification-system-pg-data:
